### ISSUE TITLE
double click bug

### ISSUE THREAD

**Issue by jredfox** [elix-x/Key-Bindings-Overhaul#1]
https://www.youtube.com/watch?v=3MKg7Q5ZYj4

bug occurs from pressing e to get out of your inventory

**Comment by Elix-x** [comment]
Known. It's because vanilla is written in derpy way. Will be fixed...

**Comment by Elix-x** [comment]
Fixed in 2.0 (Alpha as of now).

**Comment by jredfox** [comment]
nice I gues you want me to test 2 mods now?

**Comment by Elix-x** [comment]
Why???
No...
Test whatever you want...
And you were in KBO testing thread before AIC, wasn't you?

**Comment by jredfox** [comment]
No it's me themodpackmaker. I just am really busy now in days and I am limiting myself to 2 mods tops to fully test out.  Seasons is one and the other is aic2.0 I could try to test this to if you need more help. Do you have enough people currently for this mod to test?

**Comment by Elix-x** [comment]
If you can't test more mods, than Seasons and AIC, don't worry.
There are more than enough people testing KBO.
