### ISSUE TITLE
Make A Key That Makes A Key Goes Blank

### ISSUE THREAD

**Issue by jredfox** [elix-x/Key-Bindings-Overhaul#5]
Make it so that a single key that you hit or possibly even a button to the side that will make it go completely blank and not usable.

**Comment by Elix-x** [comment]
It exists. It's esc key. While setting buttons, don't press any keys, but esc. This will clear key binding and make it, as you say, unusable.

**Comment by jredfox** [comment]
well did you say that on your forum? I didn't see it there. Also make an update in the future to have a blank key button next to the right I know that would make it alot more user friendly .

**Comment by Elix-x** [comment]
Yes it's not writen on the forum... Because in vanilla to "disable" key, you have to press on key button setting and then hit esc. KBO just uses vanilla way of "disabling" key bindings. You knew that? Didn't you?

**Comment by jredfox** [comment]
ok cool didn't see it sorry for wasting your time.
