### ISSUE TITLE
Key Delay Issues(Check)

### ISSUE THREAD

**Issue by jredfox** [elix-x/Key-Bindings-Overhaul#6]
Version: 1.3
Priority: High
I could be wrong but, it appears that everything I do in vanilla is usually faster some tasks slower?
something is making everything I do in vanilla faster then it should be ( only occurs with KOB present and it doesn't happen with elix_core)

details
it use to be a delay not it seems to be faster then vanilla make
it the same delay you would have in vanilla so it has no delay either way.

jumping seems to have a delay. make all your keys universal display of the same delay at vanilla and it should fix the bug

**Comment by Elix-x** [comment]
It happens because keys are updated in pre client tick phase, which is fired by forge...
Hence, it is unfixable...

**Comment by jredfox** [comment]
I know you said you can't fix this but, is it possible to know the delay of forge to fix the delay issue and calculate all the delays so it is precisely accurate?
 **I know The_WeatherPony made a core mod called PML (Partial Mod Loader) it works around the base and ejects code live. I don't know how it works but, it could be a solution.  Either way those are your to options.**

**Comment by Elix-x** [comment]
No, delay in this case is delay of processing, which is different for every computer.
It could be computed, and avoided by multithreaded stuff, but it is not as easy as it seems.
It can also be avoided by injecting code calling keys tick exactly where usually minecraft updates them, but i try to go without core modifications.

**Comment by jredfox** [comment]
ok in the future if you want to use pml I am sure The_WeatherPony will be there.
