### ISSUE TITLE
There Are No Keybinds

### ISSUE THREAD

**Issue by jredfox** [elix-x/Key-Bindings-Overhaul#7]
Version: KeyBindingsOverhaul-ALPHA-3-2.0-1.7.10
Images: http://imgur.com/zsskJcQ

Description: I created a world and was surprised I could move but, I went to the controls and I couldn't add more then 1 key to KBO. I think you know what this is hopefully and how to fix it.

**Comment by Elix-x** [comment]
As i said, GUIs do not exist yet.
As for you could not move, delete KBO folder and options.txt inside minecraft folder and relaunch mc.
