### ISSUE TITLE
Support for other key mods (Joypad mod)

### ISSUE THREAD

**Issue by Tencao** [elix-x/Key-Bindings-Overhaul#8]
The main reason I even found and looked into this mod, is because I wanted to combine this with the joypad mod to avoid any and all key conflicts, however, using this mod completely breaks the joypad mod, so until this issue is resolved, I'd rather give players joypad support over key modifiers.

**Comment by Elix-x** [comment]
Next version (2.0) has intergated gamepad (=joypad?) support.
If you want to try it, you can join alpha testing over on mc forums.

**Comment by Tencao** [comment]
Is this for 1.7.10, or just for 1.8, and also, is there a direct link I can test the alpha at?

**Comment by Elix-x** [comment]
1.7.10.
No. There's no direct link. For alpha testing, ask on KBO mc forum page and you will be added.
